# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd).$(Rev:r)
variables:
  GO_VERSION: 1.12.5
  GOPATH: $(Agent.BuildDirectory)/go

jobs:
  - job: UnitTest
    pool:
      vmImage: ubuntu-16.04
    timeoutInMinutes: 30
    steps:
    - template: azp-dependencies.yml
    - checkout: self
    - script: |
        # TODO: remove when fabric-mod supports sampleconfig outside GOPATH
        mkdir -p ${GOPATH}/src/github.com/trustbloc/bloc-node/pkg/ledger/fabric/testutil/sampleconfig
        cp -R pkg/ledger/fabric/testutil/sampleconfig ${GOPATH}/src/github.com/trustbloc/bloc-node/pkg/ledger/fabric/testutil
        make unit-test
      displayName: Run checks and unit test

  - job: BDDTest
    pool:
      vmImage: ubuntu-16.04
    timeoutInMinutes: 30
    steps:
    - template: azp-dependencies.yml
    - checkout: self
    - script: make bddtests
      displayName: Run BDD tests
